/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
        label: ["Manrope", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        editorial: "0 20px 40px -15px rgba(26, 28, 25, 0.06)",
      },
      colors: {
        background: "#fafaf5",
        tertiary: "#131900",
        "surface-container-low": "#f4f4ef",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e3de",
        secondary: "#6c5b4e",
        "surface-bright": "#fafaf5",
        "on-surface": "#1a1c19",
        "inverse-surface": "#2f312e",
        "tertiary-fixed": "#dde9a9",
        "surface-tint": "#496455",
        "surface-variant": "#e3e3de",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "on-secondary-container": "#726153",
        "on-background": "#1a1c19",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b0cdbb",
        "surface-container-high": "#e8e8e3",
        "primary-container": "#173124",
        "secondary-fixed": "#f6decd",
        "primary-fixed": "#ccead6",
        "secondary-fixed-dim": "#d9c2b2",
        "on-primary-container": "#7d9988",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#324c3e",
        "on-secondary-fixed": "#25190f",
        "surface-container-lowest": "#ffffff",
        surface: "#fafaf5",
        "outline-variant": "#c3c8c1",
        "on-tertiary-fixed-variant": "#414b1b",
        "surface-dim": "#dadad5",
        "surface-container": "#eeeee9",
        "on-primary-fixed": "#062014",
        "tertiary-fixed-dim": "#c1cd8f",
        outline: "#737973",
        "on-surface-variant": "#434843",
        "on-secondary-fixed-variant": "#534437",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#181e00",
        primary: "#021c10",
        "inverse-on-surface": "#f1f1ec",
        "primary-fixed-dim": "#b0cdbb",
        "on-secondary": "#ffffff",
        "tertiary-container": "#262f02",
        "secondary-container": "#f6decd",
        "on-tertiary-container": "#8d985f",
      },
    },
  },
  plugins: [],
};
